import { ReactNode } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './header/Header'

type Props = {
    children: ReactNode
}

const Layout = ({ children }: Props) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>
                <div>{children}</div>
            </main>

            <footer className={styles.footer}>jjjj
            </footer>
        </div>
    )
}

export default Layout
