import { ReactNode } from 'react'
import Head from 'next/head'
import styles from '@styles/home.module.scss'
import Header from './header/Header'

type Props = {
    children: ReactNode
}

const Layout = ({ children }: Props) => {
    return (
        <div className={styles.layout_root}>
            <Head>
                <title>works sharing</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>{children}</main>
            <footer className={styles.footer}>
                <p>@Works-Sharing</p>
            </footer>
        </div>
    )
}

export default Layout
